name: boilerplate
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ui  widgets
  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.4
  pin_code_fields: ^7.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_secure_storage: ^4.1.0

  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.0.1
  shimmer: ^2.0.0
  introduction_screen: ^3.0.2
  fluttertoast: ^8.0.9

  # othe utils
  equatable: ^2.0.0
  device_preview:
  form_field_validator: ^1.1.0

  # state management
  flutter_bloc: 8.0.1
  logger:

  # network
  dio: ^4.0.0
  http: ^0.13.3
  connectivity: ^3.0.4

  # nottifications and firebase
  firebase_core: ^1.19.1
  firebase_messaging: 
  flutter_local_notifications: 
  # flutter_facebook_auth: ^4.3.4+2
  google_sign_in: ^5.3.3
  firebase_auth: 3.4.1
  # data persistence
  shared_preferences: ^2.0.5

  # file system and path
  image_picker: ^0.7.4
  file_picker: ^3.0.1

  # localization
  easy_localization: ^3.0.0

  #github forks

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0

flutter:
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/

  uses-material-design: true

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
